import React, { useState } from 'react';
import { Character } from '../types';
import { CharacterService, createCharacterDraft } from '../services/character';
import { CharacterForm } from './CharacterForm';
import { Copy, LockKeyhole, Pencil, Plus, Trash2, X } from 'lucide-react';

interface CharacterManagerProps { characters: Character[]; onChange: (characters: Character[]) => void; onClose: () => void; }
export function CharacterManager({ characters, onChange, onClose }: CharacterManagerProps) {
  const [editing, setEditing] = useState<Character | null>(null);
  const [creating, setCreating] = useState(false);
  const custom = characters.filter(CharacterService.isCustom);
  const save = (character: Character) => { const saved = character.id ? CharacterService.update(character) : CharacterService.create(character); onChange(characters.some((item) => item.id === saved.id) ? characters.map((item) => item.id === saved.id ? saved : item) : [...characters, saved]); setEditing(null); setCreating(false); };
  const duplicate = (character: Character) => { const copy = CharacterService.duplicate(character); onChange([...characters, copy]); };
  const remove = (character: Character) => { if (!window.confirm('شخصیت «' + character.displayName + '» حذف شود؟')) return; CharacterService.remove(character.id); onChange(characters.filter((item) => item.id !== character.id)); };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-2xl rounded-3xl border border-white/10 bg-[#2a1740] p-5 text-amber-50 shadow-2xl sm:p-7"><div className="mb-6 flex items-start justify-between"><div><p className="text-xs uppercase tracking-[0.2em] text-amber-300/60">Character System</p><h2 className="mt-1 text-2xl font-bold text-amber-200">مدیریت شخصیت‌ها</h2><p className="mt-2 text-sm text-amber-50/60">شخصیت‌های اصلی از داده‌ی پروژه می‌آیند؛ شخصیت‌های جدید فقط در مرورگر شما ذخیره می‌شوند.</p></div><button type="button" onClick={onClose} className="rounded-full p-2 text-amber-100/60 hover:bg-white/10 hover:text-white"><X className="h-5 w-5" /></button></div>{(creating || editing) ? <CharacterForm initial={editing || createCharacterDraft()} onSave={save} onCancel={() => { setEditing(null); setCreating(false); }} /> : <><div className="space-y-3">{characters.map((character) => <div key={character.id} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-black/10 p-3"><img src={character.avatar.source} alt="" className="h-14 w-12 rounded-xl object-cover" referrerPolicy="no-referrer" /><div className="min-w-0 flex-1"><p className="truncate font-bold text-amber-100">{character.displayName}</p><p className="text-xs text-amber-50/50">{CharacterService.isCustom(character) ? 'شخصیت سفارشی · قابل ویرایش' : 'شخصیت اصلی · فقط خواندنی'}</p></div>{CharacterService.isCustom(character) ? <><button type="button" onClick={() => setEditing(character)} title="ویرایش" className="rounded-lg p-2 text-amber-200/70 hover:bg-white/10 hover:text-amber-200"><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => duplicate(character)} title="کپی" className="rounded-lg p-2 text-amber-200/70 hover:bg-white/10 hover:text-amber-200"><Copy className="h-4 w-4" /></button><button type="button" onClick={() => remove(character)} title="حذف" className="rounded-lg p-2 text-rose-300/70 hover:bg-rose-500/10 hover:text-rose-300"><Trash2 className="h-4 w-4" /></button></> : <LockKeyhole className="mr-2 h-4 w-4 text-amber-100/30" />}</div>)}</div>{custom.length === 0 && <p className="mt-4 text-center text-sm text-amber-50/45">هنوز شخصیت سفارشی نساخته‌اید.</p>}<button type="button" onClick={() => setCreating(true)} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-amber-500 px-4 py-3 font-bold text-[#21102e] transition hover:bg-amber-400"><Plus className="h-5 w-5" /> افزودن شخصیت</button></>}</div></div>;
}
